filename = "milkyway"
zone_width = 0.1
n_stars = 1
simple = false
verbose = false
N_star_tot = 204600
migration_mode = "cbrt"
migration = "gaussian"
save_migration = false
mode = "sfr"
imf = "kroupa"
timestep = 0.02
t_d_ia = 0.040 # 40 Myr
RIa = "liam"
smoothing = 0
tau_ia = 1.5
m_upper = 100
m_lower = 0.08
sf_law = "J21"
Re = 5
sfh_model = "insideout"
max_sf_radius = 15.5
M_star_MW = 51_700_000_000.0
thin_disk_scale_radius = 2.5
thick_disk_scale_radius = 2.0
thin_to_thick_ratio = 3.7
r_sun = 8.122
MH_grad_R0 = 5
MH_grad_MH0 = 0.29
MH_grad_in = -0.015
MH_grad_out = -0.09
eta_scale = 1.0
r = 0.4
tau_star_sfh_grad = 0

[sfh_kwargs]
tau_sfh = "sanchez"
tau_rise = 2

[sf_law_kwargs]
present_day_molecular = 2.0

[migration_kwargs]
sigma_r8 = 2.68
tau_power = 0.33
R_power = 0.61
hz_s = 0.24
